services:
  - type: web
    name: gym-membership-system
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn gym_membership_system.wsgi:application
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: WEB_CONCURRENCY
        value: "2"
      # Render sets these for you, but you can override or add custom domains:
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: gym-membership-db
          property: connectionString

databases:
  - name: gym-membership-db
    plan: free
